version: "3.9"

services:
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend              
      dockerfile: Dockerfile          
    volumes:
      - ./backend:/app                
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   command: npm run dev